development:
  adapter: async
  # url: redis://certain-ice-redis:6379/1

test:
  adapter: test
  url: redis://certain-ice-redis:6379/1

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://certain-ice-redis:6379/1" } %>
  channel_prefix: api_production
